### ISSUE TITLE
Créer fonction pour envoyer une demande d'adhésion à une équipe

### ISSUE THREAD

**Issue by CharlesAF** [KenJoelTL/DefiLectureTp1#28]
Il faut qu'un participant puisse envoyer une demande d'adhésion à une équipe (c'est le capitaine qui recevra la demande)
Ensuite le capitaine peut refuser ou non la demande.

**Comment by KenJoelTL** [comment]
Points manquant en ce moment :
   * Limiter le nombre de demandes produites à **une équipe par un participant à 1**
   * Afficher la liste des demandes
   * Le capitaine qui reçoit la demande doit pourvoir l'accepter
