### ISSUE TITLE
Ajouter les POINTS au participant

### ISSUE THREAD

**Issue by CharlesAF** [KenJoelTL/DefiLectureTp1#31]
- Ajouter les points des lectures au participant
- Ajouter les points des défis au participant

**Comment by KenJoelTL** [comment]
Les minutes gagnées dans un défi doivent affecter non seulement le nombre de points(minutes) du participant, mais aussi les points de contribution à l'équipe.

**Comment by CharlesAF** [comment]
Les points sont maintenant ajoutés au participant, et dans la table demande_equipe (pour les contributions à l'équipe)
- Reste à implémenter les différences de points entre une lecture obligatoire ou non
- Implementer l'ajout de points après avoir fait un defi

**Comment by CharlesAF** [comment]
L'ajout des points du défi est fait dans le branche-CA, restera à faire le merge avec le master
