### ISSUE TITLE
Problème affichage jeu de caractères

### ISSUE THREAD

**Issue by CharlesAF** [KenJoelTL/DefiLectureTp1#34]
Les caractères "spéciaux" (éèî etc) stockés dans la base de données ne s'affiche pas correctement.

**Comment by KenJoelTL** [comment]
# Résolution
## Pour stocker et lire des données
1.  Ajouter dans le URL vers la base de données : **?useUnicode=true&characterEncoding=UTF-8**
    * > *Exemple : jdbc:mysql://localhost/nomDeLaBD```?useUnicode=true&characterEncoding=UTF-8```*
1. Changer l'encodage dans la base de données en UTF-8 Unicode si nécéssaire pour que les caractères des données existantes dans la BD puissent être lues et stockés dans le bon format.

## Pour enregistrer des données
Étant donné que les ***Strings*** dans Java ne sont pas dans le encodés format UTF-8 par défaut. Donc, sans modification, il est impossible d'enregistrer des caractères comme è, é ou ì dans un bon état. 

**La solution à ce problème est tel :**
1. Obtenir le **tableau de *bytes*** qui compose la chaîne qui est un ***String***.
1.  Construire un nouvel objet ***String*** à partir du **tableau de *bytes*** obtenu précédemment  et spécifier son jeu de caractères (*charset*) que l'on veut. 
L'objet obtenu sera une copie du ***String*** de départ

>String(byte[] bytes, String charsetName)
Constructs a new String by decoding the specified array of bytes using the specified charset.

Ou bien

>String(byte[] bytes, Charset charset)
Constructs a new String by decoding the specified array of bytes using the specified charset.

### Pour plus de renseignement, voir la classe com.util.Util.java de ce projet

*Sources*
Liste de CharsetName : https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html:
String : https://docs.oracle.com/javase/7/docs/api/java/lang/String.html
